name: datascience
channels:
  - conda-forge
dependencies:
  - altair
  - conda-build
  - cython
  - ipython
  - jupyterlab==2.1.2
  - nodejs
  - scikit-learn
  - pandas
  - pip
  - pymc3
  - python=3.8
  - sympy
  - vega_datasets
  - pip:
    - streamlit
