name: vinh
channels:
  - conda-forge
dependencies:
  - altair
  - conda-build
  - ipython
  - jupyterlab
  - jupytext
  - scikit-learn
  - pandas
  - pip
  - pymc3
  - pyright
  - python=3.10
  - sympy
  - vega_datasets
  - pip:
    - flake8
    - graphviz
    - streamlit
