#:schema https://docs.jj-vcs.dev/latest/config-schema.json
[user]
name = "Vinh Chuc"
email = "vinh.chuc@gmail.com"

[ui]
editor = "nvim"
default-command = ["log", "-r", "descendants(trunk()::present(@), 5) | tracked_remote_bookmarks()"]
