vim.keymap.set("n", "<C-p>", ":Telescope find_files<cr>", {remap = false})
vim.keymap.set("n", "<leader>fr", ":Telescope lsp_references<cr>", {remap = false})
vim.keymap.set("n", "<leader>g", ":Telescope live_grep<cr>", {remap = false})
vim.keymap.set("n", "<leader>fb", ":Telescope buffers<cr>", {remap = false})
vim.keymap.set("n", "<leader>fh", ":Telescope help_tags<cr>", {remap = false})
